//! Shell completion scripts, generated from the same clap command the binary
//! parses with, so they cannot drift from the real flags.

use clap_complete::shells::Shell;
use std::ffi::OsStr;
#[cfg(target_os = "macos")]
use std::os::unix::ffi::OsStrExt;
use std::path::{Path, PathBuf};

/// The completion script for `shell`. The leading stamp is what the per-run
/// self-setup compares before overwriting an installed file, and what tells a
/// hand-written script apart from a generated one.
pub fn script_for(shell: Shell) -> String {
    let mut cmd = crate::cli_command();
    let mut buf = Vec::new();
    clap_complete::generate(shell, &mut cmd, "videre", &mut buf);
    format!(
        "# generated by videre {}\n{}",
        env!("CARGO_PKG_VERSION"),
        String::from_utf8_lossy(&buf)
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scripts_are_stamped_and_non_empty_for_every_shell() {
        for shell in [Shell::Bash, Shell::Zsh, Shell::Fish] {
            let script = script_for(shell);
            let head: String = script.chars().take(30).collect();
            assert!(
                script.starts_with("# generated by videre "),
                "{shell:?}: {head}"
            );
            assert!(script.len() > 200, "{shell:?}: suspiciously short script");
        }
    }

    /// Shells spell long flags differently (fish completes `-l flag` without
    /// the dashes), so the flag-coverage check runs on bash, where a missing
    /// flag is literally missing text.
    #[test]
    fn the_bash_script_covers_every_long_flag_of_the_live_cli() {
        let script = script_for(Shell::Bash);
        let cmd = crate::cli_command();
        let mut long_flags: Vec<String> = cmd
            .get_arguments()
            .filter_map(|a| a.get_long())
            .map(|f| format!("--{f}"))
            .collect();
        long_flags.sort();
        long_flags.dedup();
        for flag in long_flags {
            assert!(script.contains(&flag), "{flag} is missing from the script");
        }
    }
}

// ---- self-setup -----------------------------------------------------------
//
// The ticket's rule: nobody sets completion up, and every install method ends
// with videre itself putting the script where the running shell looks for it.

/// The shells the self-setup installs for: the ones with a per-user completion
/// directory their rc already loads. zsh has none by default, so it is
/// documented instead of written.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TargetShell {
    Bash,
    Fish,
}

impl TargetShell {
    fn script(&self) -> String {
        script_for(match self {
            TargetShell::Bash => Shell::Bash,
            TargetShell::Fish => Shell::Fish,
        })
    }

    fn path(&self, home: &Path) -> PathBuf {
        match self {
            TargetShell::Bash => home
                .join(".local/share/bash-completion/completions")
                .join("videre.bash"),
            TargetShell::Fish => home.join(".config/fish/completions").join("videre.fish"),
        }
    }

    fn from_executable(name: &str) -> Option<Self> {
        let base = Path::new(name).file_name()?.to_str()?.to_ascii_lowercase();
        if base.starts_with("bash") {
            Some(TargetShell::Bash)
        } else if base.starts_with("fish") {
            Some(TargetShell::Fish)
        } else {
            None
        }
    }
}

/// What [`install_for`] did with the installed file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InstallOutcome {
    /// Written: the file was missing, or carried an older generation stamp.
    Installed,
    /// Already the current script.
    Current,
    /// A file videre did not generate, left untouched.
    LeftAlone,
}

/// Write the script for `shell` under `home`, unless a current one is there or
/// the file that is there was not generated by videre. Never fails silently
/// silently: the caller (the per-run hook) swallows the error.
pub fn install_for(shell: TargetShell, home: &Path) -> std::io::Result<InstallOutcome> {
    let path = shell.path(home);
    let script = shell.script();
    let stamp = script.lines().next().unwrap_or_default().to_owned();
    if let Ok(existing) = std::fs::read_to_string(&path) {
        match existing.lines().next() {
            Some(first) if first == stamp => return Ok(InstallOutcome::Current),
            // An older videre's stamp: ours, out of date, replaced below.
            Some(first) if first.starts_with("# generated by videre ") => {}
            Some(_) if !existing.trim().is_empty() => {
                // A file videre did not generate: a hand-written script cannot
                // be told from a foreign one, so it is never overwritten.
                return Ok(InstallOutcome::LeftAlone);
            }
            _ => {} // empty: replace below
        }
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&path, script)?;
    Ok(InstallOutcome::Installed)
}

/// The per-run hook: install the script for the shell videre is running
/// under, silently. Every failure is the caller's none.
pub fn self_setup() {
    let Some(shell) = detect_shell() else {
        return;
    };
    let Some(home) = std::env::var_os("HOME").map(PathBuf::from) else {
        return;
    };
    let _ = install_for(shell, &home);
}

/// The shell videre is running under: the parent process when it is a
/// supported shell, else `$SHELL` (the login shell, which can be stale after
/// a switch). `None` when neither names an installable shell, including zsh,
/// which is documented rather than written.
pub fn detect_shell() -> Option<TargetShell> {
    detect_shell_in(parent_executable(), std::env::var_os("SHELL").as_deref())
}

fn detect_shell_in(
    parent: Option<String>,
    shell_env: Option<&std::ffi::OsStr>,
) -> Option<TargetShell> {
    let from_env = shell_env.and_then(|s| s.to_str().map(str::to_owned));
    for name in [parent, from_env].into_iter().flatten() {
        if let Some(shell) = TargetShell::from_executable(&name) {
            return Some(shell);
        }
        // zsh is recognized but not installed for; it ends the search so an
        // unrecognized parent does not fall through to a stale $SHELL.
        let base = Path::new(&name)
            .file_name()
            .and_then(|f| f.to_str())
            .map(|f| f.to_ascii_lowercase())
            .unwrap_or_default();
        if base.starts_with("zsh") {
            return None;
        }
    }
    None
}

/// The executable name of videre's parent process.
fn parent_executable() -> Option<String> {
    let ppid = unsafe { libc::getppid() };
    if ppid <= 1 {
        return None;
    }
    #[cfg(target_os = "linux")]
    {
        std::fs::read_to_string(format!("/proc/{ppid}/comm"))
            .ok()
            .map(|s| s.trim().to_owned())
    }
    #[cfg(target_os = "macos")]
    {
        let mut buf = [0u8; 1024];
        let n = unsafe { libc::proc_pidpath(ppid, buf.as_mut_ptr().cast(), buf.len() as u32) };
        if n <= 0 {
            return None;
        }
        let path = std::ffi::OsStr::from_bytes(&buf[..n as usize]);
        Path::new(path)
            .file_name()
            .map(|s| s.to_string_lossy().into_owned())
    }
    #[cfg(not(any(target_os = "linux", target_os = "macos")))]
    {
        None
    }
}

#[cfg(test)]
mod self_setup_tests {
    use super::*;
    use std::fs;

    const OLDER_STAMP: &str = "# generated by videre 0.1.0\n";

    fn prior(home: &Path, shell: TargetShell, body: &str) -> PathBuf {
        let path = shell.path(home);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, body).unwrap();
        path
    }

    #[test]
    fn self_setup_installs_missing_replaces_older_leaves_unstamped() {
        let current_stamp = script_for(Shell::Fish);
        let cases: Vec<(Option<&str>, InstallOutcome, bool)> = vec![
            // (prior file body, expected outcome, expect the current script)
            (None, InstallOutcome::Installed, true),
            (Some(OLDER_STAMP), InstallOutcome::Installed, true),
            (Some(&current_stamp), InstallOutcome::Current, false),
            (
                Some("my own hand-written completion\n"),
                InstallOutcome::LeftAlone,
                false,
            ),
        ];
        for (idx, (body, outcome, expect_current)) in cases.into_iter().enumerate() {
            let home = tempfile::tempdir().unwrap();
            if let Some(body) = body {
                prior(home.path(), TargetShell::Fish, body);
            }
            let path = TargetShell::Fish.path(home.path());
            let before = std::fs::read(&path);
            let got = install_for(TargetShell::Fish, home.path()).unwrap();
            assert_eq!(got, outcome, "case {idx}");
            let after = fs::read_to_string(&path).unwrap();
            if expect_current {
                assert_eq!(
                    after.lines().next(),
                    script_for(Shell::Fish).lines().next(),
                    "case {idx}"
                );
            } else if let Ok(before) = before {
                assert_eq!(
                    String::from_utf8(before).unwrap(),
                    after,
                    "case {idx}: the file must be untouched"
                );
            }
        }
    }

    #[test]
    fn an_unwritable_directory_fails_loudly_to_the_caller() {
        let home = tempfile::tempdir().unwrap();
        let completions = home.path().join(".config/fish/completions");
        fs::create_dir_all(&completions).unwrap();
        let mut perms = fs::metadata(&completions).unwrap().permissions();
        std::os::unix::fs::PermissionsExt::set_mode(&mut perms, 0o555);
        fs::set_permissions(&completions, perms).unwrap();
        assert!(install_for(TargetShell::Fish, home.path()).is_err());
    }

    #[test]
    fn the_detection_falls_back_to_the_shell_variable() {
        use std::ffi::OsStr;
        assert_eq!(
            detect_shell_in(Some("/bin/bash".into()), None),
            Some(TargetShell::Bash)
        );
        assert_eq!(
            detect_shell_in(Some("/usr/local/bin/fish-3.7".into()), None),
            Some(TargetShell::Fish)
        );
        // zsh is recognized, and stops the search: a stale $SHELL must not
        // put a bash script somewhere a zsh user looks.
        assert_eq!(
            detect_shell_in(Some("/usr/bin/zsh".into()), Some(OsStr::new("/bin/bash"))),
            None
        );
        assert_eq!(
            detect_shell_in(
                Some("tmux: server".into()),
                Some(OsStr::new("/usr/bin/fish"))
            ),
            Some(TargetShell::Fish)
        );
        assert_eq!(detect_shell_in(None, None), None);
    }
}

// ---- dynamic candidates (second slice) ------------------------------------
//
// Under clap_complete's CompleteEnv mode, these run while the user types, so
// they open the library read-only and answer empty on anything that is not a
// readable library. No write lock, no download, no error path a user sees.

use clap_complete::engine::CompletionCandidate;

/// The library under the invocation directory, read-only, or nothing: shell
/// completion has no `--library` flag to honor, so it reads the default.
fn completion_ctx() -> Option<videre_core::library::LibraryContext> {
    let cwd = std::env::current_dir().ok()?;
    let home = std::env::var_os("HOME").map(PathBuf::from)?;
    videre_core::library::LibraryContext::new(&cwd, &home.join(".cache/videre")).ok()
}

fn prefix_filtered(
    current: &OsStr,
    values: impl Iterator<Item = (String, Option<String>)>,
) -> Vec<CompletionCandidate> {
    let current = current.to_string_lossy();
    values
        .filter(|(value, _)| value.starts_with(current.as_ref()))
        .map(|(value, help)| {
            let mut c = CompletionCandidate::new(value);
            if let Some(help) = help {
                c = c.help(Some(help.into()));
            }
            c
        })
        .collect()
}

/// People for `--person`: the identity and, when set, the display name.
pub fn person_candidates(current: &OsStr) -> Vec<CompletionCandidate> {
    let Some(ctx) = completion_ctx() else {
        return Vec::new();
    };
    let Ok(conn) = videre_core::library_db::open_existing_read_only(&ctx) else {
        return Vec::new();
    };
    let Ok(mut stmt) = conn.prepare("SELECT name, full_name FROM people") else {
        return Vec::new();
    };
    let Ok(rows) = stmt.query_map([], |r| {
        Ok((r.get::<_, String>(0)?, r.get::<_, Option<String>>(1)?))
    }) else {
        return Vec::new();
    };
    let values = rows.flatten().flat_map(|(name, full)| {
        let mut both = vec![(name.clone(), full.clone())];
        if let Some(full) = full {
            both.push((full, Some(name)));
        }
        both
    });
    prefix_filtered(current, values)
}

/// Models for `--model`: the ones this library already has embeddings for,
/// plus the built-in default.
pub fn model_candidates(current: &OsStr) -> Vec<CompletionCandidate> {
    let Some(ctx) = completion_ctx() else {
        return Vec::new();
    };
    let mut models = vec![(
        videre_core::embeddings::DEFAULT_MODEL_ID.to_string(),
        Some("default".to_string()),
    )];
    if let Ok(slugs) = videre_core::embeddings_db::list_models_in(&ctx) {
        for slug in slugs {
            models.push((videre_core::embeddings_db::model_from_slug(&slug), None));
        }
    }
    prefix_filtered(current, models.into_iter())
}

fn distinct_column_candidates(column: &'static str) -> impl Fn(&OsStr) -> Vec<CompletionCandidate> {
    move |current| {
        let Some(ctx) = completion_ctx() else {
            return Vec::new();
        };
        let Ok(conn) = videre_core::library_db::open_existing_read_only(&ctx) else {
            return Vec::new();
        };
        let Ok(mut stmt) = conn.prepare(&format!(
            "SELECT DISTINCT {column} FROM file_hashes WHERE {column} IS NOT NULL ORDER BY {column}"
        )) else {
            return Vec::new();
        };
        let Ok(rows) = stmt.query_map([], |r| Ok((r.get::<_, String>(0)?, None::<String>))) else {
            return Vec::new();
        };
        prefix_filtered(current, rows.flatten())
    }
}

pub fn ext_candidates(current: &OsStr) -> Vec<CompletionCandidate> {
    distinct_column_candidates("ext")(current)
}

pub fn mime_candidates(current: &OsStr) -> Vec<CompletionCandidate> {
    distinct_column_candidates("mime")(current)
}
