//! Shell completion scripts, generated from the same clap command the binary
//! parses with, so they cannot drift from the real flags.

use clap_complete::shells::Shell;

/// The completion script for `shell`. The leading stamp is what the per-run
/// self-setup compares before overwriting an installed file, and what tells a
/// hand-written script apart from a generated one.
pub fn script_for(shell: Shell) -> String {
    let mut cmd = crate::cli_command();
    let mut buf = Vec::new();
    clap_complete::generate(shell, &mut cmd, "videre", &mut buf);
    format!(
        "# generated by videre {}\n{}",
        env!("CARGO_PKG_VERSION"),
        String::from_utf8_lossy(&buf)
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scripts_are_stamped_and_non_empty_for_every_shell() {
        for shell in [Shell::Bash, Shell::Zsh, Shell::Fish] {
            let script = script_for(shell);
            let head: String = script.chars().take(30).collect();
            assert!(
                script.starts_with("# generated by videre "),
                "{shell:?}: {head}"
            );
            assert!(script.len() > 200, "{shell:?}: suspiciously short script");
        }
    }

    /// Shells spell long flags differently (fish completes `-l flag` without
    /// the dashes), so the flag-coverage check runs on bash, where a missing
    /// flag is literally missing text.
    #[test]
    fn the_bash_script_covers_every_long_flag_of_the_live_cli() {
        let script = script_for(Shell::Bash);
        let cmd = crate::cli_command();
        let mut long_flags: Vec<String> = cmd
            .get_arguments()
            .filter_map(|a| a.get_long())
            .map(|f| format!("--{f}"))
            .collect();
        long_flags.sort();
        long_flags.dedup();
        for flag in long_flags {
            assert!(script.contains(&flag), "{flag} is missing from the script");
        }
    }
}
