//! Shell completion scripts, generated from the same clap command the binary
//! parses with, so they cannot drift from the real flags.

use clap_complete::shells::Shell;
use std::ffi::OsStr;
#[cfg(target_os = "macos")]
use std::os::unix::ffi::OsStrExt;
use std::path::{Path, PathBuf};

/// The completion script for `shell`. The leading stamp is what the per-run
/// self-setup compares before overwriting an installed file, and what tells a
/// hand-written script apart from a generated one.
pub fn script_for(shell: Shell) -> String {
    let mut cmd = crate::cli_command();
    let mut buf = Vec::new();
    clap_complete::generate(shell, &mut cmd, "videre", &mut buf);
    format!(
        "# generated by videre {}\n{}",
        env!("CARGO_PKG_VERSION"),
        String::from_utf8_lossy(&buf)
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scripts_are_stamped_and_non_empty_for_every_shell() {
        for shell in [Shell::Bash, Shell::Zsh, Shell::Fish] {
            let script = script_for(shell);
            let head: String = script.chars().take(30).collect();
            assert!(
                script.starts_with("# generated by videre "),
                "{shell:?}: {head}"
            );
            assert!(script.len() > 200, "{shell:?}: suspiciously short script");
        }
    }

    /// Shells spell long flags differently (fish completes `-l flag` without
    /// the dashes), so the flag-coverage check runs on bash, where a missing
    /// flag is literally missing text.
    #[test]
    fn the_bash_script_covers_every_long_flag_of_the_live_cli() {
        let script = script_for(Shell::Bash);
        let cmd = crate::cli_command();
        let mut long_flags: Vec<String> = cmd
            .get_arguments()
            .filter_map(|a| a.get_long())
            .map(|f| format!("--{f}"))
            .collect();
        long_flags.sort();
        long_flags.dedup();
        for flag in long_flags {
            assert!(script.contains(&flag), "{flag} is missing from the script");
        }
    }
}

// ---- self-setup -----------------------------------------------------------
//
// The ticket's rule: nobody sets completion up, and every install method ends
// with videre itself putting the script where the running shell looks for it.

/// The shells the self-setup installs for: the ones with a per-user completion
/// directory their rc already loads. zsh has none by default, so it is
/// documented instead of written.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TargetShell {
    Bash,
    Fish,
}

impl TargetShell {
    fn script(&self) -> String {
        script_for(match self {
            TargetShell::Bash => Shell::Bash,
            TargetShell::Fish => Shell::Fish,
        })
    }

    fn path(&self, home: &Path) -> PathBuf {
        match self {
            TargetShell::Bash => home
                .join(".local/share/bash-completion/completions")
                .join("videre.bash"),
            TargetShell::Fish => home.join(".config/fish/completions").join("videre.fish"),
        }
    }

    fn from_executable(name: &str) -> Option<Self> {
        let base = Path::new(name).file_name()?.to_str()?.to_ascii_lowercase();
        if base.starts_with("bash") {
            Some(TargetShell::Bash)
        } else if base.starts_with("fish") {
            Some(TargetShell::Fish)
        } else {
            None
        }
    }
}

/// What [`install_for`] did with the installed file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InstallOutcome {
    /// Written: the file was missing, or carried an older generation stamp.
    Installed,
    /// Already the current script.
    Current,
    /// A file videre did not generate, left untouched.
    LeftAlone,
}

/// Write the script for `shell` under `home`, unless a current one is there or
/// the file that is there was not generated by videre. Never fails silently
/// silently: the caller (the per-run hook) swallows the error.
pub fn install_for(shell: TargetShell, home: &Path) -> std::io::Result<InstallOutcome> {
    let path = shell.path(home);
    let script = shell.script();
    let stamp = script.lines().next().unwrap_or_default().to_owned();
    if let Ok(existing) = std::fs::read_to_string(&path) {
        match existing.lines().next() {
            Some(first) if first == stamp => return Ok(InstallOutcome::Current),
            // An older videre's stamp: ours, out of date, replaced below.
            Some(first) if first.starts_with("# generated by videre ") => {}
            Some(_) if !existing.trim().is_empty() => {
                // A file videre did not generate: a hand-written script cannot
                // be told from a foreign one, so it is never overwritten.
                return Ok(InstallOutcome::LeftAlone);
            }
            _ => {} // empty: replace below
        }
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&path, script)?;
    Ok(InstallOutcome::Installed)
}

/// The per-run hook: install the script for the shell videre is running
/// under, silently. Every failure is the caller's none.
pub fn self_setup() {
    let Some(shell) = detect_shell() else {
        return;
    };
    let Some(home) = std::env::var_os("HOME").map(PathBuf::from) else {
        return;
    };
    let _ = install_for(shell, &home);
}

/// The shell videre is running under: the parent process when it is a
/// supported shell, else `$SHELL` (the login shell, which can be stale after
/// a switch). `None` when neither names an installable shell, including zsh,
/// which is documented rather than written.
pub fn detect_shell() -> Option<TargetShell> {
    detect_shell_in(parent_executable(), std::env::var_os("SHELL").as_deref())
}

fn detect_shell_in(
    parent: Option<String>,
    shell_env: Option<&std::ffi::OsStr>,
) -> Option<TargetShell> {
    let from_env = shell_env.and_then(|s| s.to_str().map(str::to_owned));
    for name in [parent, from_env].into_iter().flatten() {
        if let Some(shell) = TargetShell::from_executable(&name) {
            return Some(shell);
        }
        // zsh is recognized but not installed for; it ends the search so an
        // unrecognized parent does not fall through to a stale $SHELL.
        let base = Path::new(&name)
            .file_name()
            .and_then(|f| f.to_str())
            .map(|f| f.to_ascii_lowercase())
            .unwrap_or_default();
        if base.starts_with("zsh") {
            return None;
        }
    }
    None
}

/// The executable name of videre's parent process.
fn parent_executable() -> Option<String> {
    let ppid = unsafe { libc::getppid() };
    if ppid <= 1 {
        return None;
    }
    #[cfg(target_os = "linux")]
    {
        std::fs::read_to_string(format!("/proc/{ppid}/comm"))
            .ok()
            .map(|s| s.trim().to_owned())
    }
    #[cfg(target_os = "macos")]
    {
        let mut buf = [0u8; 1024];
        let n = unsafe { libc::proc_pidpath(ppid, buf.as_mut_ptr().cast(), buf.len() as u32) };
        if n <= 0 {
            return None;
        }
        let path = std::ffi::OsStr::from_bytes(&buf[..n as usize]);
        Path::new(path)
            .file_name()
            .map(|s| s.to_string_lossy().into_owned())
    }
    #[cfg(not(any(target_os = "linux", target_os = "macos")))]
    {
        None
    }
}

#[cfg(test)]
mod self_setup_tests {
    use super::*;
    use std::fs;

    const OLDER_STAMP: &str = "# generated by videre 0.1.0\n";

    fn prior(home: &Path, shell: TargetShell, body: &str) -> PathBuf {
        let path = shell.path(home);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, body).unwrap();
        path
    }

    #[test]
    fn self_setup_installs_missing_replaces_older_leaves_unstamped() {
        let current_stamp = script_for(Shell::Fish);
        let cases: Vec<(Option<&str>, InstallOutcome, bool)> = vec![
            // (prior file body, expected outcome, expect the current script)
            (None, InstallOutcome::Installed, true),
            (Some(OLDER_STAMP), InstallOutcome::Installed, true),
            (Some(&current_stamp), InstallOutcome::Current, false),
            (
                Some("my own hand-written completion\n"),
                InstallOutcome::LeftAlone,
                false,
            ),
        ];
        for (idx, (body, outcome, expect_current)) in cases.into_iter().enumerate() {
            let home = tempfile::tempdir().unwrap();
            if let Some(body) = body {
                prior(home.path(), TargetShell::Fish, body);
            }
            let path = TargetShell::Fish.path(home.path());
            let before = std::fs::read(&path);
            let got = install_for(TargetShell::Fish, home.path()).unwrap();
            assert_eq!(got, outcome, "case {idx}");
            let after = fs::read_to_string(&path).unwrap();
            if expect_current {
                assert_eq!(
                    after.lines().next(),
                    script_for(Shell::Fish).lines().next(),
                    "case {idx}"
                );
            } else if let Ok(before) = before {
                assert_eq!(
                    String::from_utf8(before).unwrap(),
                    after,
                    "case {idx}: the file must be untouched"
                );
            }
        }
    }

    #[test]
    fn an_unwritable_directory_fails_loudly_to_the_caller() {
        let home = tempfile::tempdir().unwrap();
        let completions = home.path().join(".config/fish/completions");
        fs::create_dir_all(&completions).unwrap();
        let mut perms = fs::metadata(&completions).unwrap().permissions();
        std::os::unix::fs::PermissionsExt::set_mode(&mut perms, 0o555);
        fs::set_permissions(&completions, perms).unwrap();
        assert!(install_for(TargetShell::Fish, home.path()).is_err());
    }

    #[test]
    fn the_detection_falls_back_to_the_shell_variable() {
        use std::ffi::OsStr;
        assert_eq!(
            detect_shell_in(Some("/bin/bash".into()), None),
            Some(TargetShell::Bash)
        );
        assert_eq!(
            detect_shell_in(Some("/usr/local/bin/fish-3.7".into()), None),
            Some(TargetShell::Fish)
        );
        // zsh is recognized, and stops the search: a stale $SHELL must not
        // put a bash script somewhere a zsh user looks.
        assert_eq!(
            detect_shell_in(Some("/usr/bin/zsh".into()), Some(OsStr::new("/bin/bash"))),
            None
        );
        assert_eq!(
            detect_shell_in(
                Some("tmux: server".into()),
                Some(OsStr::new("/usr/bin/fish"))
            ),
            Some(TargetShell::Fish)
        );
        assert_eq!(detect_shell_in(None, None), None);
    }
}

// ---- dynamic candidates (second slice) ------------------------------------
//
// Under clap_complete's CompleteEnv mode, these run while the user types, so
// they open the library read-only and answer empty on anything that is not a
// readable library. No write lock, no download, no error path a user sees.

use clap_complete::engine::CompletionCandidate;

/// The library the completion candidates come from: the one named by the
/// invocation's own `--library` flag (the shell passes the typed words to the
/// completer), else the library under the invocation directory. Read-only, or
/// nothing when the root is not a library.
fn completion_ctx() -> Option<videre_core::library::LibraryContext> {
    let cwd = std::env::current_dir().ok()?;
    let home = std::env::var_os("HOME").map(PathBuf::from)?;
    let args: Vec<std::ffi::OsString> = std::env::args_os().skip(1).collect();
    let root = library_root_in(&args, &home).unwrap_or_else(|| cwd.clone());
    let root = if root.is_absolute() {
        root
    } else {
        cwd.join(root)
    };
    videre_core::library::LibraryContext::new(&root, &home.join(".cache/videre")).ok()
}

/// The value of a `--library` flag on the line being completed.
fn library_root_in(args: &[std::ffi::OsString], home: &Path) -> Option<PathBuf> {
    // Every shell calls the completer as `videre -- <the words you typed>`:
    // the typed words, the program name repeated first and any flags
    // including --library, are what follows the -- separator. Nothing before
    // it is the user's line.
    let separator = args.iter().position(|a| a == "--")?;
    let mut waiting = false;
    for arg in args.get(separator + 2..)? {
        let arg = arg.to_string_lossy().into_owned();
        if waiting {
            return Some(as_shell_would_pass(&arg, home));
        }
        if arg == "--library" {
            waiting = true;
        } else if let Some(value) = arg.strip_prefix("--library=") {
            return Some(as_shell_would_pass(value, home));
        }
    }
    None
}

/// A typed word as the shell would have passed it to a real run. The words a
/// completer receives are unexpanded, so `~/photos` arrives with its tilde and
/// a quoted path with its quotes.
fn as_shell_would_pass(word: &str, home: &Path) -> PathBuf {
    let word = ['"', '\'']
        .iter()
        .find_map(|q| word.strip_prefix(*q)?.strip_suffix(*q))
        .unwrap_or(word);
    if word == "~" {
        home.to_path_buf()
    } else if let Some(rest) = word.strip_prefix("~/") {
        home.join(rest)
    } else {
        PathBuf::from(word)
    }
}

#[cfg(test)]
mod library_flag_tests {
    use super::*;

    fn root_for(typed: &[&str]) -> Option<PathBuf> {
        let mut args: Vec<std::ffi::OsString> = vec!["--".into(), "videre".into()];
        args.extend(typed.iter().map(Into::into));
        library_root_in(&args, Path::new("/home/ayşe"))
    }

    #[test]
    fn the_library_flag_is_read_as_the_shell_would_expand_it() {
        let expected = Some(PathBuf::from("/home/ayşe/Fotoğraflar"));
        for typed in [
            ["--library", "~/Fotoğraflar"],
            ["--library", "\"~/Fotoğraflar\""],
            ["--library", "'/home/ayşe/Fotoğraflar'"],
            ["--library=~/Fotoğraflar", "search"],
        ] {
            assert_eq!(root_for(&typed), expected, "{typed:?}");
        }
        assert_eq!(
            root_for(&["--library", "arşiv"]),
            Some(PathBuf::from("arşiv"))
        );
        assert_eq!(root_for(&["search", "--person", "ay"]), None);
    }

    #[test]
    fn no_typed_words_is_no_library_not_a_panic() {
        assert_eq!(library_root_in(&["--".into()], Path::new("/h")), None);
    }
}

fn prefix_filtered(
    current: &OsStr,
    values: impl Iterator<Item = (String, Option<String>)>,
) -> Vec<CompletionCandidate> {
    let current = current.to_string_lossy().to_lowercase();
    values
        .filter(|(value, _)| value.to_lowercase().starts_with(current.as_str()))
        .map(|(value, help)| {
            let mut c = CompletionCandidate::new(value);
            if let Some(help) = help {
                c = c.help(Some(help.into()));
            }
            c
        })
        .collect()
}

/// People for `--person`: the identity, space-free, because bash inserts a
/// completion without quoting and a display name with a space would split
/// the line. The display name rides along as the candidate's help text.
pub fn person_candidates(current: &OsStr) -> Vec<CompletionCandidate> {
    key_values(current, "person")
}

/// A key's values from the library, as `videre::query_lang::values` gives
/// them to the query and the gallery, for a flag with the same meaning.
fn key_values(current: &OsStr, key: &str) -> Vec<CompletionCandidate> {
    let Some(ctx) = completion_ctx() else {
        return Vec::new();
    };
    let Ok(conn) = videre_core::library_db::open_existing_read_only(&ctx) else {
        return Vec::new();
    };
    let values = videre::query_lang::values(&conn, key, "")
        .into_iter()
        .map(|v| {
            let help = (v.label != v.value).then_some(v.label);
            (v.value, help)
        });
    prefix_filtered(current, values)
}

/// Models for `--model`: the ones this library already has embeddings for,
/// plus the built-in default.
pub fn model_candidates(current: &OsStr) -> Vec<CompletionCandidate> {
    let Some(ctx) = completion_ctx() else {
        return Vec::new();
    };
    let mut models = vec![(
        videre_core::embeddings::DEFAULT_MODEL_ID.to_string(),
        Some("default".to_string()),
    )];
    if let Ok(slugs) = videre_core::embeddings_db::list_models_in(&ctx) {
        for slug in slugs {
            models.push((videre_core::embeddings_db::model_from_slug(&slug), None));
        }
    }
    prefix_filtered(current, models.into_iter())
}

pub fn ext_candidates(current: &OsStr) -> Vec<CompletionCandidate> {
    key_values(current, "ext")
}

pub fn mime_candidates(current: &OsStr) -> Vec<CompletionCandidate> {
    key_values(current, "mime")
}

/// The query's last term, for `search`'s query and `--query`: keys, the
/// library's values, operators, from `videre::query_lang::suggest`, the
/// function the gallery's box uses.
pub fn query_candidates(current: &OsStr) -> Vec<CompletionCandidate> {
    let Some(ctx) = completion_ctx() else {
        return Vec::new();
    };
    let Ok(conn) = videre_core::library_db::open_existing_read_only(&ctx) else {
        return Vec::new();
    };
    query_candidates_in(&conn, &current.to_string_lossy())
        .into_iter()
        .map(|(value, help)| CompletionCandidate::new(value).help(help.map(Into::into)))
        .collect()
}

/// Each candidate is the whole query up to the cursor, as the shell replaces
/// the whole word. Measured in bash 5.2, zsh 5.9 and fish 3.7, Tab inside an
/// open single quote:
///
/// - bash passes the word without its open quote, zsh and fish with it, so
///   one leading quote is dropped; every shell then closes the quote itself;
/// - zsh and fish escape or drop a candidate that does not extend the typed
///   text literally, so only those that do are offered: `place:Ka` gets no
///   `place:"Kadıköy, İstanbul"`, while `place:` and `place:"Ka` do;
/// - a lone candidate is completed and its quote closed, so a single key
///   (`tag:`) is replaced by its values, keeping the quote open for them.
fn query_candidates_in(
    conn: &rusqlite::Connection,
    current: &str,
) -> Vec<(String, Option<String>)> {
    let typed = current.strip_prefix(['\'', '"']).unwrap_or(current);
    let suggest = |text: &str| {
        let s = videre::query_lang::suggest(conn, text, text.chars().count(), 200);
        let head: String = text.chars().take(s.start).collect();
        (head, s.items)
    };
    let (mut head, mut items) = suggest(typed);
    if let [only] = items.as_slice() {
        if only.kind == videre::query_lang::SuggestionKind::Key {
            let keyed = format!("{head}{}", only.insert);
            let (h, values) = suggest(&keyed);
            if !values.is_empty() {
                (head, items) = (h, values);
            }
        }
    }
    items
        .into_iter()
        .map(|i| {
            let value = i
                .insert
                .split_once(':')
                .map_or("", |(_, v)| v.trim_matches('"'));
            let help = match (i.count, i.label != value) {
                (Some(n), true) => Some(format!("{} ({n})", i.label)),
                (Some(n), false) => Some(n.to_string()),
                (None, _) => None,
            };
            (format!("{head}{}", i.insert), help)
        })
        .filter(|(candidate, _)| candidate.starts_with(typed))
        .collect()
}

#[cfg(test)]
mod query_completion_tests {
    use super::*;

    /// A library with two tags, one person and one place with a space in it.
    fn conn() -> (tempfile::TempDir, rusqlite::Connection) {
        let temp = tempfile::tempdir().unwrap();
        let root = temp.path().join("arşiv");
        std::fs::create_dir(&root).unwrap();
        let ctx = videre_core::library::LibraryContext::new(&root, &temp.path().join("c")).unwrap();
        let conn = videre_core::library_db::initialize(&ctx).unwrap();
        let root = ctx.paths.root.display().to_string();
        conn.execute_batch(&format!(
            "INSERT INTO file_hashes (path, hash, ext, mime, location_name) VALUES
               ('{root}/a.jpg', 'h_a', 'jpg', 'image/jpeg', 'Kadıköy, İstanbul'),
               ('{root}/b.jpg', 'h_b', 'jpg', 'image/jpeg', NULL);
             INSERT INTO photo_tags VALUES ('h_a', 'deniz'), ('h_b', 'dağ');
             INSERT INTO people (name, full_name) VALUES ('erhan_gundogan', 'Erhan Gündoğan');
             INSERT INTO faces (hash, bbox, embedding, person_label, confirmed) VALUES
               ('h_a', '0,0,9,9', X'00', 'erhan_gundogan', 1);"
        ))
        .unwrap();
        (temp, conn)
    }

    fn got(current: &str) -> Vec<String> {
        let (_t, conn) = conn();
        query_candidates_in(&conn, current)
            .into_iter()
            .map(|(value, _)| value)
            .collect()
    }

    #[test]
    fn the_open_quote_zsh_and_fish_pass_is_not_part_of_the_query() {
        // bash hands over the word without its open quote, zsh and fish with.
        for typed in ["tag:de", "'tag:de", "\"tag:de"] {
            assert_eq!(got(typed), ["tag:deniz"], "{typed}");
        }
        assert_eq!(got("'gün tag:den"), ["gün tag:deniz"]);
    }

    #[test]
    fn a_candidate_is_the_query_up_to_the_cursor_and_extends_what_was_typed() {
        assert_eq!(got("'person:erh"), ["person:erhan_gundogan"]);
        // Matches in the gallery, but would not extend the typed text, which
        // zsh and fish then mangle: left out here.
        assert!(got("'person:gündo").is_empty());
        assert_eq!(got("'place:"), ["place:\"Kadıköy, İstanbul\""]);
        assert_eq!(got("'place:\"Ka"), ["place:\"Kadıköy, İstanbul\""]);
        assert!(got("'place:Ka").is_empty());
    }

    #[test]
    fn a_single_key_offers_its_values_so_the_shell_does_not_close_the_quote() {
        assert_eq!(got("'ta"), ["tag:dağ", "tag:deniz"]);
        assert_eq!(got("'-ta"), ["-tag:dağ", "-tag:deniz"]);
        // Several keys: the keys themselves.
        assert!(got("'p").contains(&"person:".to_string()));
    }

    #[test]
    fn a_person_carries_the_display_name_as_help() {
        let (_t, conn) = conn();
        let c = query_candidates_in(&conn, "'person:e");
        assert_eq!(c[0].1.as_deref(), Some("Erhan Gündoğan (1)"));
    }
}
